### ISSUE TITLE
sklearn is deprecated -- use scikit-learn instead

### ISSUE THREAD

**Issue by SterlingYM** [PetroFit/petrofit#186]
PyPi package ```sklearn``` is deprecated (see https://pypi.org/project/sklearn/). This raises an exception when importing the package (e.g., ```from sklearn.tree import DecisionTreeRegressor``` in ```petrosian.py```:9). Please consider switching to ```scikit-learn``` instead.

**Comment by robelgeda** [comment]
Thank you! I am planning on introducing major upgrades for v0.5.0 soon (hoping within the next two weeks) and will make sure this is fixed!

**Comment by robelgeda** [comment]
I just realized that it has been fixed by #174!

**Comment by SterlingYM** [comment]
Sorry for the duplicate, I didn't realize there was an existing pull request. Looking at #174, however, I only see the ```setup.cfg``` being changed, and this does not actually solve the problem as Petrofit still tries to import ```sklearn```.

**Comment by robelgeda** [comment]
Thank you for pointing that, I am going to reopen this ticket because we may need to update and release a minor version for 0.4.x.

**Comment by robelgeda** [comment]
Thank you so much, I just realized this was a bug and that the import statement was not removed during the last refactor. This was actually a bug in the main branch not v0.4.1. #192 fixes the issue.
